// Codemap orchestrator — runs static extraction, optional runtime enrichment, constraint mining,
// then emits CODEMAP.md (human) and .agent-boost/codemap.json (machine).
import path from 'node:path';
import { extractStatic } from './static.mjs';
import { ingestRuntime } from './runtime.mjs';
import { mineConstraints } from './constraints.mjs';
import { ensureDir, writeJson, writeText } from '../utils.mjs';

export async function buildCodeMap({ repoRoot, withRuntime = false }) {
  const entries = await extractStatic(repoRoot);
  const withConstraints = await mineConstraints(repoRoot, entries);
  let enriched = withConstraints;
  if (withRuntime) {
    try {
      enriched = await ingestRuntime(repoRoot, enriched);
    } catch (e) {
      // Runtime is best-effort; static still ships.
      console.warn(`codemap: runtime enrichment skipped — ${e?.message || e}`);
    }
  }

  const data = {
    version: 1,
    generatedAt: new Date().toISOString(),
    repoRoot,
    entries: enriched,
  };

  await ensureDir(path.join(repoRoot, '.agent-boost'));
  await writeJson(path.join(repoRoot, '.agent-boost', 'codemap.json'), data);

  const md = renderMarkdown(data);
  await writeText(path.join(repoRoot, 'CODEMAP.md'), md);

  return data;
}

function renderMarkdown(data) {
  const lines = [];
  lines.push('# Code Map');
  lines.push('');
  lines.push(`_Generated by token-flux at ${data.generatedAt}. Do not edit by hand — regenerate with_ `);
  lines.push('`node ./.agent-boost/scripts/build-codemap.mjs`.');
  lines.push('');
  lines.push(`_${data.entries.length} file(s) indexed._`);
  lines.push('');

  // Group by top-level directory.
  const byDir = new Map();
  for (const e of data.entries) {
    const parts = e.path.split(/[\\/]/);
    const key = parts.length > 1 ? parts[0] : '(root)';
    if (!byDir.has(key)) byDir.set(key, []);
    byDir.get(key).push(e);
  }

  const sortedDirs = [...byDir.keys()].sort();
  for (const dir of sortedDirs) {
    lines.push(`## ${dir}`);
    lines.push('');
    for (const e of byDir.get(dir).sort((a, b) => a.path.localeCompare(b.path))) {
      renderEntry(lines, e);
    }
    lines.push('');
  }
  return lines.join('\n') + '\n';
}

function renderEntry(lines, e) {
  const purpose = e.purpose ? ` — ${e.purpose}` : '';
  lines.push(`### ${e.path}${purpose}`);
  if (e.loc != null) {
    const complexity = e.complexity != null ? `, cx ${e.complexity}` : '';
    lines.push(`_${e.loc} LOC${complexity}_`);
  }
  if (e.imports && e.imports.length) {
    lines.push('');
    lines.push('**imports:** ' + e.imports.slice(0, 12).map((i) => `\`${i}\``).join(', ') + (e.imports.length > 12 ? ' …' : ''));
  }
  if (e.exports && e.exports.length) {
    lines.push('');
    lines.push('**exports:**');
    for (const sym of e.exports) {
      const annotations = [];
      if (sym.callCount != null) annotations.push(`called ${sym.callCount}×`);
      if (sym.coverage != null) annotations.push(`cov ${sym.coverage}%`);
      if (sym.callers && sym.callers.length) annotations.push(`${sym.callers.length} caller(s)`);
      if (sym.throws && sym.throws.length) annotations.push(`throws: ${sym.throws.slice(0, 3).join(', ')}`);
      if (sym.preconditions && sym.preconditions.length) annotations.push(`${sym.preconditions.length} precondition(s)`);
      if (sym.isDead) annotations.push('WARNING: possibly dead code');
      if (sym.isUntested) annotations.push('WARNING: untested');
      const annot = annotations.length ? ` _(${annotations.join(', ')})_` : '';
      lines.push(`- \`${sym.signature}\`${annot}`);
    }
  }
  if (e.sideEffects && e.sideEffects.length) {
    lines.push('');
    lines.push('**side-effects:** ' + e.sideEffects.slice(0, 8).map((s) => `\`${s}\``).join(', '));
  }
  lines.push('');
}
