// Aider adapter — writes .aider.conf.yml with read directives so CODEMAP/LESSONS auto-load.
import path from 'node:path';
import { writeText, readText, exists, PKG_ROOT } from '../utils.mjs';
import { loadAgentTemplate } from './index.mjs';

export async function writeAider({ repoRoot, config }) {
  const agentMd = await loadAgentTemplate(config);
  await writeText(path.join(repoRoot, 'AGENT.md'), agentMd);

  const confPath = path.join(repoRoot, '.aider.conf.yml');
  const lines = [
    '# Generated by token-flux. Auto-loads the code map and lessons into every session.',
    'read:',
    '  - AGENT.md',
    '  - CODEMAP.md',
    '  - LESSONS.md',
    '',
  ];
  if (!(await exists(confPath))) {
    await writeText(confPath, lines.join('\n'));
  } else {
    // Append read entries if missing. Minimal YAML touch — leave other user config alone.
    const current = await readText(confPath);
    if (!current.includes('AGENT.md')) {
      await writeText(confPath, current.trimEnd() + '\n\n' + lines.join('\n'));
    }
  }
}
