// Cline adapter — writes .clinerules at repo root.
import path from 'node:path';
import { readText, writeText, PKG_ROOT } from '../utils.mjs';
import { loadAgentTemplate } from './index.mjs';

export async function writeCline({ repoRoot, config }) {
  const agentMd = await loadAgentTemplate(config);
  const header = '# Cline rules — generated by token-flux\n\n';
  await writeText(path.join(repoRoot, '.clinerules'), header + agentMd);
}
